version: "3.1"
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:alpine
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: demo_db
    volumes:
      - ./pgsql/initdb:/docker-entrypoint-initdb.d # 啟動初期設定
      - ./pgsql/datadir:/var/lib/postgresql/data # 資料庫資料儲存位置
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - .:/var/lib/redis/data

  # nginx:
  #   container_name: go-nginx
  #   restart: always
  #   build: ./docker/nginx/
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - .:/Applications
  #     - ./nginx-logs:/var/log/nginx